### ISSUE TITLE
Please add documentation on how to run this?

### ISSUE THREAD

**Issue by wheatbread** [AzerPUG/Preparation-CheckList#13]
Hi!  It says this is standalone, but I could not find in the description how to run it without AzerPug Core.

**Comment by Arco-Dielhof** [comment]
Try the slash command: `/azp pcl` or `/azp check`. Both should work.
I am sorry I must have forgotten to add that to the CF Description. I will do that tomorrow when I wake up ^^
(If I do not forget........)

**Comment by Arco-Dielhof** [comment]
Added to the description now as well, closing issue.
Thanx for reporting this ^^
